name: test

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node and pnpm
        uses: ./.github/actions/setup-node-pnpm
        with:
          working-directory: .

      - name: Build
        run: corepack pnpm -r build

      - name: Test core
        working-directory: packages/core
        run: corepack pnpm test

      - name: Test CLI
        working-directory: packages/cli
        run: corepack pnpm test
